env:
    es2021: true
    node: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: latest
    sourceType: module
plugins:
    - '@typescript-eslint'
    - 'prettier'
rules:
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - never
    'no-explicit-any': true
    'no-unused-vars': 0
    'no-var-requires': true
    prettier/prettier: 'error'
    arrow-body-style": 'off'
    prefer-arrow-callback: 'warn'
