mode: development

general:
  frontendDomain: 'https://localhost:6100/#'

application:
  host: 'http://localhost'
  bearer: 'Bearer'
  bearerHeader: 'authorization'
  apiKeyHeader: 'api-key'
  information: false
  request:
    allowMethods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE']
    ignoreCheckMethods: []
    ignoreApiKey: []
    ignoreToken: []

job:
  activeCronJobs: [] # ["sample-job"]
  activeConsumers: [] # ["sample-consumer-queue"]

logger:
  logOnConsole: true
  logOnFile: false
  logOnDatabase: false
  winston:
    dirname: 'logs'
    datePattern: 'YYYY-MM-DD'
    extension: '.log'
    zippedArchive: true
    maxSize: '20m'
    maxFiles: '14d'

database:
  mongodb:
    name: 'backend_solution'
    default_collection: 'default'
    uri: 'mongodb://0.0.0.0:27017'
  postgres:
    user: 'postgres'
    host: '0.0.0.0'
    database: 'backend_solution'
    password: 'postgres'
    port: 5432
    idleTimeoutMillis: 10000
    connectionTimeoutMillis: 10000
    ssl:
      rejectUnauthorized: false
  redis:
    uri: 'redis://localhost:6379'
  ioRedis:
    host: 'localhost'
    port: 6379
    showFriendlyErrorStack: true
    enableReadyCheck: true
    maxRetriesPerRequest: null

cors:
  optionsSuccessStatus: 200
  origin: '*'
  methods: ['POST']

helmet:
  contentSecurityPolicy:
    useDefaults: true
    reportOnly: true
  crossOriginEmbedderPolicy: true
  crossOriginOpenerPolicy: true
  crossOriginResourcePolicy: true
  dnsPrefetchControl: true
  expectCt: true
  frameguard: true
  hidePoweredBy: true
  hsts: true
  ieNoOpen: true
  noSniff: true
  originAgentCluster: true
  permittedCrossDomainPolicies: true
  referrerPolicy: true
  xssFilter: true

rate_limiter:
  windowMs: 60_000
  max: 1_000
  standardHeaders: true
  legacyHeaders: false

upload:
  # use “tmp" to use os tmp directory
  tempDir: 'public/tmp'
  # The directory for placing file uploads in. You can move them later by using fs.rename()
  uploadDir: 'public'
  validUploadFolders: []
  responsePath: 'http://localhost'
  # to include the extensions of the original files or not
  keepExtensions: true
  # when you call the .parse method, the files argument (of the callback) will contain arrays of files for inputs which submit multiple files using the HTML5 multiple attribute. Also, the fields argument will contain arrays of values for fields that have names ending with '[]'
  multiples: true
  # the minium size of uploaded file
  minFileSize: 1
  # limit the amount of uploaded files, set Infinity for unlimited
  maxFiles: 2
  # limit the size of uploaded file - 2 * 1024 * 1024
  maxFileSize: 2097152
  # limit the size of the batch of uploaded files - 5 * 1024 * 1024
  maxTotalFileSize: 10485760
  # limit the number of fields, set 0 for unlimited
  maxFields: 100
  # limit the amount of memory all fields together (except files) can allocate in bytes - 20 * 1024 * 1024
  maxFieldsSize: 20971520
